# Generated by Django 5.2 on 2025-05-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('second_number', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operation', models.CharField(choices=[('+', 'Adição'), ('-', 'Subtração'), ('*', 'Multiplicação'), ('/', 'Divisão')], max_length=1)),
                ('result', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Operação',
                'verbose_name_plural': 'Histórico de Operações',
                'ordering': ['-created_at'],
            },
        ),
    ]
